// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"➥","status":true,"description":"=== Sistema de Batalha ===","parameters":{}},
{"name":"AS_BattlePositions","status":true,"description":"[v1.1.0] (Core Refeito) Sistema de posicionamento adaptativo baseado apenas em GRID com multi-boss automático e IA de ajuste. - AncientSouls","parameters":{"EnableAdaptiveGrid":"true","MinColumns":"1","MaxColumns":"1","AdaptiveIntervalFrames":"30","BossEnemyIds":"[\"5\"]","BossAdvanceEnabled":"true","BossAdvanceFactor":"0.12","EnableDebugOverlay":"true","DebugVerbose":"true"}}
];
